### ISSUE TITLE
Can not change the year and month by the drop down

### ISSUE THREAD

**Issue by karthick678** [vickramravichandran/angular-datepicker-light#1]
Your datepicker plugins in nice...but i can not change the month and year by the drop down.Once i change the year and month the popup close automatically..

**Comment by vickramravichandran** [comment]
What browser are you using? Just now I tried on Chrome and Safari and it works fine.

**Comment by karthick678** [comment]
I think http://vickramravichandran.github.io/angular-datepicker-light/  is demo url..You just hit the url..then go to the first example try to change the month and year..For example if u change the month the model value won't change and your popup will close automatically...

**Comment by vickramravichandran** [comment]
Are you using IE/FireFox/Chrome/Safari? I am unable to reproduce this issue on Chrome or Safari. When I change either the month or year the popup does not close and the calendar updates to show the selected Month and Year.

**Comment by karthick678** [comment]
I did check IE. it is working fine.but the issue on chrome.

**Comment by vickramravichandran** [comment]
I am not able to reproduce this issue. I remember having this issue long ago. Can you clear the browser cache and try again.
