### ISSUE TITLE
buildCalendar() is not available on controller

### ISSUE THREAD

**Issue by ritujain1000** [vickramravichandran/angular-datepicker-light#2]
<img width="1440" alt="screen shot 2016-10-13 at 10 07 20 am" src="https://cloud.githubusercontent.com/assets/1575030/19359159/c07f09ec-912d-11e6-9b21-bc2b3560dbc5.png">

buildCalendar() is called on controller from refresh method. It is undefined on controller. Attached is the screenshot for the same.

**Comment by vickramravichandran** [comment]
Fixed.
